using AQFED, Test
import AQFED.Black

include("basket_test.jl")
include("pln_european_test.jl")
include("iv_tests.jl")
include("collocation_tests.jl")
include("american_test.jl")
include("random_tests.jl")
include("asian_test.jl")
include("fdm_test.jl")
include("fdmbarrier_test.jl")
include("lvg_test.jl")
include("varswap_test.jl")
include("mc_tests.jl")
include("ssobol_tests.jl")
include("mixmax_tests.jl")
#include("rough_test.jl")
#include("sabr_test.jl")
#include("vol_calibration_tests.jl")
